# **importing pandas**

In [ ]:
## importing pandas
import pandas as pd

# **Opening a local csv file**

In [ ]:
## Opening a local csv file
df=pd.read_csv('/content/transactions.csv')
df.head()

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS

# **Opening a csv file from an URL**

In [ ]:
## Opening a csv file from an URL
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
# | Source              | Example                                                                    |
# | ------------------- | -------------------------------------------------------------------------- |
# | Direct CSV URL      | `pd.read_csv('https://example.com/data.csv')`                              |
# | GitHub Raw File     | `pd.read_csv('https://raw.githubusercontent.com/user/repo/main/file.csv')` |
# | Kaggle Download URL | `pd.read_csv('URL')` *(if publicly accessible)*                            |
# | Local File          | `pd.read_csv('/content/file.csv')`                                         |


import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

req = requests.get(url)
data = StringIO(req.text)

df = pd.read_csv(
    data,
    usecols=['Country', 'Region'],
    nrows=20,
    index_col='Country'
)

print(df.head())

          Region
Country
Algeria   AFRICA
Angola    AFRICA
Benin     AFRICA
Botswana  AFRICA
Burkina   AFRICA

# Sep **Parameter**  : Specifies the delimiter (separator) used in the file

In [ ]:
## Sep Parameter
pd.read_csv('/content/india-districts-census-2011.csv',sep=None)

/tmp/ipykernel_4741/2777259013.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  pd.read_csv('/content/india-districts-census-2011.csv',sep=None)

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816,19143,22673,36470,16610,19860,144,...,2316,4309,1370,838,2208,576,978,1554,1446,10027
636,637,PONDICHERRY,Karaikal,200222,97809,102413,154916,79903,75013,35348,...,1063,2408,665,340,1005,246,483,729,341,4890
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,15397,9935,0,...,685,1895,212,134,346,70,120,190,84,3151
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,43186,35497,0,...,685,1895,212,134,346,70,120,190,84,3151
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,105794,84472,0,...,1371,3020,649,368,1017,265,497,762,376,5782

In [ ]:
# sep parameter examples

# Comma           -> sep=','
# Semicolon       -> sep=';'
# Tab             -> sep='\t'
# Pipe            -> sep='|'
# Colon           -> sep=':'
# Space           -> sep=' '
# Multiple Spaces -> sep=r'\s+'
# Hyphen          -> sep='-'
# Underscore      -> sep='_'
# Tilde           -> sep='~'
# Caret           -> sep='^'
# Hash            -> sep='#'
# Dollar          -> sep='$'
# At Sign         -> sep='@'
# Custom String   -> sep='abc'                                              |     |


##Most common

# | Rank | Separator | `sep`            |    |
# | ---- | --------- | ---------------- | -- |
# | 1    | Comma     | `','`            |    |
# | 2    | Semicolon | `';'`            |    |
# | 3    | Tab       | `'\t'`           |    |
# | 4    | Pipe      | `'               | '` |
# | 5    | Space     | `' '` / `r'\s+'` |    |

In [ ]:
# df = pd.read_csv(
#     '/content/transactions.csv',
#     header=None,
#     names=['TransactionID', 'CustomerID', 'Amount']
# )

# This is used when the CSV does not have a header row and you want to provide your own column names.

# **Index_col parameter : index_col tells Pandas which column should be used as the DataFrame index.**

In [ ]:
## index_col parameter

pd.read_csv('/content/transactions.csv',sep=None,index_col='Sender UPI ID')

/tmp/ipykernel_4741/27931537.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  pd.read_csv('/content/transactions.csv',sep=None,index_col='Sender UPI ID')

,Transaction ID,Timestamp,Sender Name,Receiver Name,Receiver UPI ID,Amount (INR),Status
Sender UPI ID,,,,,,,
4161803452@okaxis,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
8908837379@okaxis,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
4633654150@okybl,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,Diya Goel,2598130823@okicici,941.88,SUCCESS
7018842771@okhdfcbank,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
1977143985@okybl,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,Baiju Issac,5245672729@okybl,2800.55,SUCCESS
...,...,...,...,...,...,...,...
7041132054@okhdfcbank,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
1200592114@okybl,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
6922445535@okicici,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,Mishti Kala,5207563362@okybl,4857.89,FAILED
4638471232@okhdfcbank,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,Sahil Bail,9348631179@okaxis,9475.68,FAILED
0385561234@oksbi,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

# **Header parameter** :header tells Pandas which row contains the column names.

In [ ]:
## Header parameter

# | Value         | Meaning                                     |
# | ------------- | ------------------------------------------- |
# | `header=0`    | First row contains column names (default)   |
# | `header=None` | File has no column names                    |
# | `header=n`    | Use row `n` as column names (0-based index) |

pd.read_csv('temp.csv',sep=None,header=1)

# **usecols parameter** : usecols is used to read only selected columns from a CSV file.

In [ ]:
## usecols parameter

pd.read_csv('/content/transactions.csv',usecols=['Transaction ID','Amount (INR)','Status'])

                           Transaction ID  Amount (INR)   Status
0    4d3db980-46cd-4158-a812-dcb77055d0d2       3907.34   FAILED
1    099ee548-2fc1-4811-bf92-559c467ca792       8404.55  SUCCESS
2    d4c05732-6b1b-4bab-90b9-efe09d252b99        941.88  SUCCESS
3    e8df92ee-8b04-4133-af5a-5f412180c8ab       8926.00  SUCCESS
4    e7d675d3-04f1-419c-a841-7a04662560b7       2800.55  SUCCESS
..                                    ...           ...      ...
995  843d87b5-902e-4336-9438-aa76d74e13e4       9270.15  SUCCESS
996  2dbbb577-4617-44b1-9a51-5fdf18ebb2ab       2278.32   FAILED
997  7c38e684-5968-432e-8acb-5bbe0f718fad       4857.89   FAILED
998  27624b55-fd6d-45ce-bbc5-0c2958d48865       9475.68   FAILED
999  b792bf64-2047-4435-aac1-27ee95b134d6       1426.60  SUCCESS

[1000 rows x 3 columns]

In [ ]:
from numpy import squeeze
## squeeze parameters
s = pd.read_csv('/content/india-districts-census-2011.csv',usecols=['Population']).squeeze("columns")
s


s = pd.read_csv(
    '/content/india-districts-census-2011.csv',
    usecols=['Population']
)['Population']

print(type(s))
s

<class 'pandas.core.series.Series'>

0      870354
1      753745
2      133487
3      140802
4      476835
        ...
635     41816
636    200222
637     36842
638    105597
639    238142
Name: Population, Length: 640, dtype: int64

# **skiprows/nrows parameter**


*   skiprows: Skips specified rows (or the first N rows) while reading a CSV file.
*   nrows: Reads only the specified number of rows from the beginning of the CSV file.

In [ ]:
## skiprows/nrows parameter

pd.read_csv('/content/transactions.csv',skiprows=[0,1]) # skips rows based on indexing (0 based indexing)

pd.read_csv('/content/india-districts-census-2011.csv', nrows=5) #nrows tells Pandas how many rows to read from the top of the file.

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

# **Encoding parameter : encoding tells Pandas how the text in the file is encoded.**

In [ ]:
## Encoding parameter : encoding tells Pandas how the text in the file is encoded.

# | Encoding       | Usage                 |
# | -------------- | --------------------- |
# | `'utf-8'`      | Most common (default) |
# | `'latin1'`     | Western European text |
# | `'ISO-8859-1'` | Similar to latin1     |
# | `'cp1252'`     | Windows encoding      |
# | `'utf-16'`     | UTF-16 encoded files  |
# | `'utf-8-sig'`  | UTF-8 with BOM        |

# pd.read_csv('file.csv', encoding='utf-8')

pd.read_csv('zomato.csv',encoding='latin-1')

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS
...,...,...,...,...,...,...,...,...
995,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
997,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,FAILED
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,FAILED
999,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

# **skip bad lines : Used when some rows in a CSV have the wrong number of columns and cause parsing errors.**

In [ ]:
## skip bad lines : Used when some rows in a CSV have the wrong number of columns and cause parsing errors.

pd.read_csv(
    'BX-Books.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

# **dtype: Specifies the data type for one or more columns while reading a CSV file, helping control memory usage and ensuring correct data types.**

In [ ]:
## dtype parameters

pd.read_csv('/content/india-districts-census-2011.csv',dtype={'District code': int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Columns: 118 entries, District code to Total_Power_Parity
dtypes: int64(116), object(2)
memory usage: 590.1+ KB

# **parse_dates: Converts specified date/time columns from string (object) to datetime64[ns] while reading a CSV file.**

In [ ]:
## Handling Dates/timestamps : Used to automatically convert date/timestamp columns from string (object) to datetime (datetime64[ns]) while reading the CSV.

pd.read_csv('/content/transactions.csv',parse_dates=['Timestamp']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   1000 non-null   object
 1   Timestamp        1000 non-null   datetime64[ns]
 2   Sender Name      1000 non-null   object
 3   Sender UPI ID    1000 non-null   object
 4   Receiver Name    1000 non-null   object
 5   Receiver UPI ID  1000 non-null   object
 6   Amount (INR)     1000 non-null   float64
 7   Status           1000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 62.6+ KB

In [ ]:
# | `parse_dates` Value                  | Purpose                                                        | Example                                                                   |
# | ------------------------------------ | -------------------------------------------------------------- | ------------------------------------------------------------------------- |
# | `['Timestamp']`                      | Convert one date column                                        | `pd.read_csv('file.csv', parse_dates=['Timestamp'])`                      |
# | `['Order_Date', 'Ship_Date']`        | Convert multiple date columns                                  | `pd.read_csv('file.csv', parse_dates=['Order_Date', 'Ship_Date'])`        |
# | `[['Year', 'Month', 'Day']]`         | Combine multiple columns into one datetime column              | `pd.read_csv('file.csv', parse_dates=[['Year', 'Month', 'Day']])`         |
# | `{'Date': ['Year', 'Month', 'Day']}` | Combine columns and give the new datetime column a custom name | `pd.read_csv('file.csv', parse_dates={'Date': ['Year', 'Month', 'Day']})` |
# | `['Timestamp', 'Order_Date']`        | Convert several date columns at once                           | `pd.read_csv('file.csv', parse_dates=['Timestamp', 'Order_Date'])`        |

# **converters : converters applies a function to every value in the specified column while reading the CSV.**

In [ ]:
## converters : converters applies a function to every value in the specified column while reading the CSV.

def status(status):
  if status=='SUCCESS':
    return 1
  return 0


pd.read_csv('/content/transactions.csv',converters={'Status' : status})

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,0
1,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,1
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,1
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,1
4,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,1
...,...,...,...,...,...,...,...,...
995,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,1
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,0
997,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,0
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,0
999,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,1

# **na_values: Specifies additional values that should be treated as missing values (NaN) while reading a CSV file.**

In [ ]:
## na_values parameter : na_values tells Pandas which values should be treated as missing values (NaN).

#  na_values specifies additional values that should be interpreted as missing (NaN) while reading a CSV file.

pd.read_csv('/content/transactions.csv',na_values=['NA', 'N/A', '?', '--'])

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS
...,...,...,...,...,...,...,...,...
995,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
997,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,FAILED
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,FAILED
999,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

In [ ]:
# | `na_values` Value                             | Meaning                              | Example                                                                          |
# | --------------------------------------------- | ------------------------------------ | -------------------------------------------------------------------------------- |
# | `'NA'`                                        | Treat `NA` as missing                | `pd.read_csv('file.csv', na_values='NA')`                                        |
# | `'?'`                                         | Treat `?` as missing                 | `pd.read_csv('file.csv', na_values='?')`                                         |
# | `['NA', '?']`                                 | Multiple missing value indicators    | `pd.read_csv('file.csv', na_values=['NA', '?'])`                                 |
# | `['NA', 'N/A', 'NULL']`                       | Multiple text values as NaN          | `pd.read_csv('file.csv', na_values=['NA', 'N/A', 'NULL'])`                       |
# | `['--', 'Unknown']`                           | Custom missing value indicators      | `pd.read_csv('file.csv', na_values=['--', 'Unknown'])`                           |
# | `{'Status':['Unknown']}`                      | Column-specific missing values       | `pd.read_csv('file.csv', na_values={'Status':['Unknown']})`                      |
# | `{'Amount':['?','NA']}`                       | Different NaN values for a column    | `pd.read_csv('file.csv', na_values={'Amount':['?','NA']})`                       |
# | `{'Status':['Unknown'], 'Amount':['?','NA']}` | Different rules for multiple columns | `pd.read_csv('file.csv', na_values={'Status':['Unknown'], 'Amount':['?','NA']})` |

0

# **chunksize: Reads a large CSV file in smaller batches (chunks) instead of loading the entire dataset into memory at once.**

In [ ]:
## Loading a huge dataset in chunks : chunksize reads a large CSV file in smaller batches (chunks) instead of loading the entire dataset into memory at once.

dfs=pd.read_csv('/content/india-districts-census-2011.csv',chunksize=210)

In [ ]:
for chunk in dfs:
  print(chunk.shape)


# Remember: After iterating through dfs once, it's exhausted. If you need it again, recreate it with pd.read_csv(..., chunksize=210).

In [ ]:
# | Without `chunksize`        | With `chunksize`            |
# | -------------------------- | --------------------------- |
# | Loads entire file into RAM | Loads small parts at a time |
# | Can cause memory errors    | Memory efficient            |
# | Slow for huge files        | Better for large datasets   |

In [ ]:
total_pop = 0

for chunk in pd.read_csv(
    '/content/india-districts-census-2011.csv',
    chunksize=210
):
    total_pop += chunk['Population'].sum()

print(total_pop)

1210854977

In [ ]:
dfs = pd.read_csv(
    '/content/india-districts-census-2011.csv',
    chunksize=210
)

df = pd.concat(dfs, ignore_index=True)
print(df.shape)

(640, 118)