In [30]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

response = requests.get("https://www.google.com")

print(response.status_code)

200

In [31]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://books.toscrape.com',headers=headers).text

In [32]:
soup=BeautifulSoup(webpage,'lxml')

In [33]:
# print(soup.prettify())

In [34]:
books = soup.find_all('article', class_='product_pod')

print(len(books))

20

In [35]:
book = books[0]

print(book.prettify())

<article class="product_pod">
 <div class="image_container">
  <a href="catalogue/a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   Â£51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

In [36]:
book.h3.a['title']

'A Light in the Attic'

In [37]:
book.find('p', class_='price_color').text

'Â£51.77'

In [38]:
book.find('p', class_='star-rating')['class'][1]

'Three'

In [39]:
book.find('p', class_='instock availability').text.strip()

'In stock'

In [40]:
book.find('img')['src']

'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg'

In [41]:
titles = []
prices = []
ratings = []
availability = []

for book in books:

    titles.append(book.h3.a['title'])

    prices.append(
        book.find('p', class_='price_color').text
    )

    ratings.append(
        book.find('p', class_='star-rating')['class'][1]
    )

    availability.append(
        book.find(
            'p',
            class_='instock availability'
        ).text.strip()
    )

In [42]:
len(titles)

20

In [43]:
df = pd.DataFrame({
    'Title': titles,
    'Price': prices,
    'Rating': ratings,
    'Availability': availability
})

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [29]:
# data = []

# for book in books:

#     data.append({
#         'Title': book.h3.a['title'],
#         'Price': book.find('p', class_='price_color').text,
#         'Rating': book.find('p', class_='star-rating')['class'][1],
#         'Availability': book.find(
#             'p',
#             class_='instock availability'
#         ).text.strip()
#     })

# df = pd.DataFrame(data)

# **Fake Job**

In [59]:
from bs4 import BeautifulSoup
import requests

headers = {'User-Agent': 'Mozilla/5.0'}

response = requests.get(
    'https://realpython.github.io/fake-jobs/',
    headers=headers
)

print(response.status_code)

soup = BeautifulSoup(response.text, 'html.parser')

print(soup.title)

200
<title>Fake Python</title>

In [63]:
# print(soup.prettify())

In [69]:
jobs = soup.find_all("div", class_="card-content")
jobs[0]

<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Senior Python Developer</h2>
<h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>
</div>
</div>
<div class="content">
<p class="location">
        Stewartbury, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>
</footer>
</div>

In [70]:
print("Total jobs:", len(jobs))

Total jobs: 100

In [72]:
first_job = jobs[0]

title = first_job.find('h2').text.strip()
company = first_job.find('h3').text.strip()
location = first_job.find('p', class_='location').text.strip()

print(title)
print(company)
print(location)

Senior Python Developer
Payne, Roberts and Davis
Stewartbury, AA

In [74]:
jobs = soup.find_all("div", class_="card-content")

titles = []
companies = []
locations = []

for job in jobs:
    titles.append(job.find("h2").text.strip())
    companies.append(job.find("h3").text.strip())
    locations.append(job.find("p", class_="location").text.strip())

len(titles)
len(companies)
len(locations)

100

In [76]:

df = pd.DataFrame({
    "title": titles,
    "company": companies,
    "location": locations
})

df.head()

                     title                     company              location
0  Senior Python Developer    Payne, Roberts and Davis       Stewartbury, AA
1          Energy engineer            Vasquez-Davidson  Christopherville, AA
2          Legal executive  Jackson, Chambers and Levy   Port Ericaburgh, AA
3   Fitness centre manager              Savage-Bradley     East Seanview, AP
4          Product manager                 Ramirez Inc   North Jamieview, AP